uptake/pkgnet

- .Rbuildignore
- DESCRIPTION
- _pkgdown.yml
- docs/LICENSE.html
- docs/authors.html
- docs/index.html
- docs/reference/AbstractGraphReporter.html
- docs/reference/AbstractPackageReporter.html
- docs/reference/CalcNetworkFeatures.html
- docs/reference/CreatePackageReport.html
- docs/reference/DefaultReporters.html
- docs/reference/ExtractDependencyNetwork.html
- docs/reference/ExtractFunctionNetwork.html
- docs/reference/GetCoverageByFunction.html
- docs/reference/MakeGraphObject.html
- docs/reference/PackageDependencyReporter.html
- docs/reference/PackageFunctionReporter.html
- docs/reference/PlotNetwork.html
- docs/reference/index.html
This PR fixes a variety of R CMD check errors. Including CRAN-specific ones like "your package description cannot start with the phrase 'this package'"
It also fixes our `pkgdown` site. That site is not reflective of the current state of this package (it's missing a lot of functions and stuff) but it will at least now build correctly. After this PR is merged, we'll be able to see our docs on gh-pages!
> Fix misc documentation issues

- .gitignore
- .travis.yml
- R/AbstractGraphReporter.R
- R/PackageFunctionReporter.R
- R/functional_structure.R
- R/network_features.R
- R/package_report.R
- R/update_graph.R
- docs/reference/AbstractGraphReporter.html
- docs/reference/CalcNetworkFeatures.html
- docs/reference/CreatePackageReport.html
- docs/reference/ExtractFunctionNetwork.html
- docs/reference/MakeGraphObject.html
- docs/reference/PackageFunctionReporter.html
- docs/reference/PlotNetwork.html
- man/AbstractGraphReporter.Rd
- man/CalcNetworkFeatures.Rd
- man/CreatePackageReport.Rd
- man/ExtractFunctionNetwork.Rd
- man/MakeGraphObject.Rd
- man/PackageFunctionReporter.Rd
- man/PlotNetwork.Rd
- tests/testthat/test-network_features.R
- tests/testthat/test-update_graph.R
This PR contains remaining documentation changes needed for this project to pass `R CMD CHECK`. 
These aren't super important right now, but having this check working means we can prevent ourselves from doing bad things in future PRs.
> documentation changes to pass R CMD CHECk

- R/CreatePackageReport.R
- R/PackageDependencyReporter.R
- man/CreatePackageReport.Rd
- man/PackageDependencyReporter.Rd
Hi James, as part of oss hack night, I fixed a few documentation spelling errors
> Fixed a few documentation spelling errors

- R/PackageFunctionReporter.R
> Remove old commented code referring to UpdateNodes function

- DESCRIPTION
- LICENSE
- README.md
- cran-comments.md
This PR contains changes requested by CRAN for our submission. I also added the `URL` and `BugReports` fields to `DESCRIPTION` so people will see our Github link from the CRAN page for the package.
Don't merge until we get approved. I will keep pushing CRAN recommended changes onto this branch.
> Release v0.1.0

- R/PackageDependencyReporter.R
- R/PackageFunctionReporter.R
@bburns632 this is what we worked on.
> Updated get_summary_view() to round all doubles to 3 decimal places.

- .travis.yml
Two line addition to enable unit test code coverage check on PRs automatically.
> codecov in .travis.yml

- vignettes/pkgnet-intro.Rmd
- vignettes_source/pkgnet-intro.Rmd
Hello Brian, James, Jay, and Patrick,
Thanks for this wonderful package and the opportunity to submit my first PR to an open source package. Thanks!
> fixed typo

- R/CreatePackageReport.R
- R/pkgnet.R
First time I'm using github &  doing open source development, thanks for the opportunity! I added the two parameters to a null object on the central method & then invoked those using @inheritParams in the function that uses them
> I attempted to update the documentation per the example provided

- R/PackageFunctionReporter.R
Addresses #134.
`.parse_function` in `FunctionReporter` will break on complex function objects which have other functions stored as an attribute. This PR changes `.called_by` to only grab the `body` of the functions we're checking and discard any of the other stuff.
Potentially in the future we might want to consider any functions stored as attributes as dependencies. But this is an edge case and it might be hard to know how this pattern generalizes.
> Fix function parsing failure bug for complex function objects with functions as attributes

- tests/testthat/test-CreatePackageReport.R
Happy to report the test passes and didn't uncover any issues!
> Add test that CreatePackageReport respects report_path (fixes #118)

- .Rbuildignore
- README.md
- appveyor.yml
> set up appveyor testing

- README.md
Maturing lifecycle badge added.
> Added lifecycle badge (fixes #205)

- README.md
Fixes Issue #221 
(This issue reminded me that I wanted to implement the Travis-CI logo for my own repository, so I said I would do both at the same time!)
> Added Travis logo to the README badge for Travis CI status

- DESCRIPTION
- inst/milne/DESCRIPTION
- man/pkgnet-package.Rd
Change email address to personal email
> Change email address

- CONTRIBUTING.md
- cran-comments.md
- vignettes/publishing-reports.Rmd
I guess we missed these during the switch.
> updated some old UptakeOpenSource references

- man/figures/logo.svg
Thank you @mattdzugan for the conversion to SVG
> upload SVG version of the logo

- CONTRIBUTING.md
- DESCRIPTION
- NEWS.md
- README.md
- cran-comments.md
- release_testing/dockerfile
* Node coloring in DependencyReporter (#243)
* Removed LazyData field to accomodate change in CRAN policy. (#289)
* Updated release testing pipeline
* Updated Codecov URL.
> Release/0.4.2 Node Coloring Changes & Resolving CRAN Checks

- README.md
> Fix Codecov badge display

- .github/workflows/ci.yml
Adds additional CI triggers:
- Pull request
- Scheduled to run once a week
- "Workflow dispatch" adds a button to allow manual running
> Add additional CI triggers

- README.md
> Update README.md Main Branch test status

- .github/workflows/release.yml
- .github/workflows/website.yaml
> Devel Testing on Release and Website Docs Build
