README.md

I did this wrong in my previous "travis badge" PR. This is correct

added travis badge to README

---

.travis.yml
R/AbstractGraphReporter.R
R/PackageFunctionReporter.R
tests/testthat.R
tests/testthat/test-CreatePackageReport.R
tests/testthat/test-functional_structure.R

For the functional dependencies, the node list is decoupled from the edge list.  Now, graphs can have orphan nodes (functions without any dependencies or decedents) as well as no edges (all orphan functions).  Plotting is updated as well

orphan nodes and graphs with no edges

---

R/AbstractGraphReporter.R
R/PackageDependencyReporter.R
tests/testthat/test-PackageDependencyReporter.R

I changed the package dependency edge direction to the convention we agreed upon the other day.  
Run this: `t <- pkgnet::CreatePackageReport(packageName = "baseballstats")`

Edge direction

---

R/DefaultReporters.R
R/PackageSummaryReporter.R
inst/package_report/package_summary_reporter.Rmd

This reinstates the PackageSummaryReporter back into the report.  The formatting is not great, but it generates.

reinstate basic package summary reporter

---

DESCRIPTION
LICENSE
R/PackageSummaryReporter.R
_pkgdown.yml
docs/LICENSE.html
docs/authors.html
docs/index.html
docs/reference/AbstractGraphReporter.html
docs/reference/AbstractPackageReporter.html
docs/reference/DefaultReporters.html
docs/reference/PackageDependencyReporter.html
docs/reference/PackageFunctionReporter.html
docs/reference/PackageSummaryReporter.html
docs/reference/RenderPackageReport.html
docs/reference/index.html
inst/package_report/footer.html
inst/package_report/package_report.Rmd
inst/package_report/package_summary_reporter.Rmd

**Report Format Updates**
1. DT::datatable used to format package description as a table
2. Html header added to report with pkgnet repo link
3. Footer added with license info
**Repo Website Changes**
1. All functions added to reference section (this could use more organization). 
2. Theme changed to "flatly" for no good reason other than to align with report theme.
3. Authors & Contributors and License sections updated.

Update Report Format & Update Repo Website

---

R/PackageDependencyReporter.R
R/PackageFunctionReporter.R
R/PackageSummaryReporter.R
inst/package_report/package_dependency_reporter.Rmd
inst/package_report/package_function_reporter.Rmd
inst/package_report/package_summary_reporter.Rmd

- Added node tables to the report with `DT`, utilizing `get_summary_view()` functions already established. 
- Slight rearrangement and content changes to report

Add Node Tables to Report

---

R/PackageFunctionReporter.R
tests/testthat/test-PackageFunctionReporter.R

Somehow, we had both `package_test_coverage` and `calculate_test_coverage` which were identical to each other. 
Also, I surfaced network level coverage measure in the `networkMeasures` object of the `PackageFunctionReporter` along with others.  This is the first test in surfacing them in the report.

Remove Redundant Coverage Functions & Add Network Coverage Measures

---

R/AbstractGraphReporter.R
R/PackageDependencyReporter.R
R/PackageFunctionReporter.R

Fixes #84.
- Removed a bunch of unneeded explicit `calculate_network_measure` calls.
- `calculate_network_measures` inserts into cached `network_measures` list instead of overwriting.

Calculate Test Coverage bug fix

---

R/PackageDependencyReporter.R
man/AbstractGraphReporter.Rd
man/FunctionReporter.Rd

`Depends` is the strong form of package dependency and we should make it a default in `DependencyReporter`. See discussion in #95 for more details.
This will make `pkgnet` work for some of the older R packages on CRAN which still have all of their dependencies declared in Depends, such as [gbm](https://cran.r-project.org/web/packages/gbm/index.html).
Example code to test that this worked:
**fails (current state of master)**
```r
reporter <- DependencyReporter$new(
, dep_types = c("Imports")
)
reporter$set_package("gbm")
reporter$graph_viz
```
**works on this branch**
```r
reporter <- DependencyReporter$new(
, dep_types = c("Imports", "Depends")
)
reporter$set_package("gbm")
reporter$graph_viz
```
many thanks to @ShirinG for reporting this issue in [her R-bloggers …

Change default dep_types for DependencyReporter to include Depends

---

R/CreatePackageReport.R

We aren't actually silencing the logger before rendering.

fix call to silence logger

---

R/AbstractPackageReporter.R
R/CreatePackageReport.R
tests/testthat/test-AbstractPackageReporter.R
tests/testthat/test-CreatePackageReport.R
tests/testthat/test-DependencyReporter.R
tests/testthat/test-FunctionReporter.R

This PR tries to address #89 , adding a faster and more informative error for the case where someone tries to use a package that isn't locally installed.
I do not think `pkgnet` should take any responsibility for polling CRAN (to see if a package theoretically _might_ exist) or trying an installation directly. I also do not think it should expose the ability to set a custom library location.
We should just fail if a package isn't found in the default `lib.loc`.

Add more informative error on bad package name specification

---

R/AbstractGraphReporter.R
R/PackageDependencyReporter.R
R/PackageFunctionReporter.R
inst/package_report/package_dependency_reporter.Rmd
inst/package_report/package_report.Rmd
tests/testthat/test-DependencyReporter.R

This is the second of 2 PRs addressing #95 . It is possible for `DependencyReporter` to generate an empty graph if you try with a package that has no dependencies (`'base'`) or you don't specify enough dependency types to check (see discussion in #95 on how `gbm` uses only `Depends`).
My philosophy was to have `DependencyReporter` throw a fatal error, but still have `CreatePackageReport` work. I strongly believe that `CreatePackageReport` should always work even if some of the boxes get filled in with errors or are left empty.

Add more explicit handling for empty graphs

---

R/CreatePackageReport.R

h/t @patrick-boueri for helping uncover this brutal bug in `CreatePackageReport()` tonight!
`pkgnet` reports use template Rmd files that we ship with the package. When we call `rmarkdown::render()`, we pass the appropriate template path to `input` using `system.file(..., package = 'pkgnet')` to grab it from wherever the package is installed.
Per a suggestion from @mfrasco (I don't remember the exact issue/PR), a while ago we exposed `report_path` to allow people to pass a file path to write the static HTML output of `CreatePackageReport()`. We pass that value to `output_file` in `rmarkdown::render()`.
So far so good, right? Here's where things get weird.
`rmarkdown::render()` doesn't expect `output_file` to be a path to a file...it expects it to just be a name and extension! The actual …

Fix bug with `report_path`

---

.Rbuildignore
.gitignore
R/PackageFunctionReporter.R
tests/testthat/test-DependencyReporter.R
tests/testthat/test-FunctionReporter.R

- Refactored `FunctionReporter` so that node and edge extraction generate a node list in one place (in the `extract_nodes` method)
- Updated `FunctionReporter` to also include non-exported functions. Addresses #122. Sorry I forgot to put it in the commit message.
- Fixed `FunctionReporter` to properly return an empty edge data.table in the case with no edges. This can happen if you only have orphan functions. Previously it would do this only in the case where a package had one function, but in that case if there was one recursive function it would incorrectly return an empty edge table. 
- Added some RStudio project files to .gitignore and .Rbuildignore
- UPDATE: Fixed reversed edge direction and added unit test. Addresses #127

FunctionReporter to handle Non-exported Functions

---

R/PackageFunctionReporter.R

Fixes a bug where the function .parse_function used by `FunctionReporter` chokes on environment pointers.
This was discovered by finding out the following error when trying to calculate edges for the `lubridate` package:
```
Error in as.vector(x, "list") : 
cannot coerce type 'externalptr' to vector of type 'list' 
```
This is because lubridate has [this bit](https://github.com/tidyverse/lubridate/blob/ea25ca629ccd7598f2e2271146c8f551acb26096/R/POSIXt.r#L54-L57) which uses `evalqOnLoad` to register the S3 method `c.POSIXct`.
This creates some hidden functions in the lubridate namespace, one of which is the function `.__A__.1`:
```
function (env) 
eval({
registerS3method("c", "POSIXct", c.POSIXct)
}, <environment>)
```
where `<environment>` is a pointer to `<environment: …

Fixed bug with FunctionReporter and environment pointers

---

inst/package_report/package_dependency_reporter.Rmd
tests/testthat/test-CreatePackageReport.R

This PR restores the table view on the dependency network page.
I verified this by running `CreatePackageReport('ggplot2')` and visually inspecting the output. I also added a unit test to prevent a regression in the future.

Restored missing depdency table (fixes #136)

---

R/testing_utils.R

I tried this on a Windows laptop tonight and confirmed it works. I believe `where` is a core part of Windows and should be as ubiquitous in that world as `which` is in Unix-alike distributions.
Fixes #121, removing the last technical barrier to our next release. Now it's just up to us to address the other functional things called out in [the milestone](https://github.com/UptakeOpenSource/pkgnet/milestone/1).

made testing strategy portable (fixes #121)

---

R/testing_utils.R
tests/testthat.R
tests/testthat/setup_setTestEnv.R
tests/testthat/teardown_setTestEnv.R

`covr` has been broken with pkgnet for a while, since #108 was merged.
This has caused our codecov to [silently fail](https://travis-ci.org/UptakeOpenSource/pkgnet/builds/451194948) in in the Travis "after_success" build steps. 
The same error was seen when trying to run `covr::package_coverage` locally (or by trying to run `FunctionReporter` with `calculate_test_coverage`). 
This was due to the way `covr` installs the package into a temporary directory before it does all of its stuff. The directory structure in the `covr` case wasn't included in the list of directory sanitation in `.BuildTestLib`.
Additionally, because we had to install the test packages from an installed copy of `pkgnet` source rather than the raw source, the test packages had all been moved out of inst up into the root …

Fixed .BuildTestLib for covr

---

R/CreatePackageReport.R
R/PackageFunctionReporter.R
man/FunctionReporter.Rd
tests/testthat/test-CreatePackageReport.R
tests/testthat/test-FunctionReporter.R

- Resolves #126.
- `.parse_function` and `.parse_R6_expression` will ignore the righthand side `bar` of expressions like `foo$bar`. This means if someone names a list item the same as a function in the package namespace, `FunctionReporter` won't think references to it are calls to the same-named function.
- Added a "Known Limitations" section to roxygen documention for `FunctionReporter` addressing non-standard evaluation, among others.
- Added unit tests for `.parse_function` and `.parse_R6_expression`
- Added a `PKGNET_SUPPRESS_BROWSER` env variable so that running the tests won't keep opening baesballstats package reports in the browser.

FunctionReporter handling of list extraction symbols

---

R/testing_utils.R

This PR resolves two issues we had with CRAN testing our 0.3.0 submission.
---
- Added case for test_x64 to .BuildTestLib for some Windows cases
We had the following ERROR in our 0.3.0 submission to CRAN for Windows.
This is because we aren't catch the `test_x64` case, which seems to be when Windows is using 64-bit R and explicitly calling it out in the directory names. 
From `R CMD check`:
```
Warning: invalid package 'd:/RCompile/CRANincoming/R-devel/pkgnet.Rcheck/tests_x64//baseballstats'
Warning: invalid package 'd:/RCompile/CRANincoming/R-devel/pkgnet.Rcheck/tests_x64//sartre'
Warning: invalid package 'd:/RCompile/CRANincoming/R-devel/pkgnet.Rcheck/tests_x64//milne'
Warning: invalid package 'd:/RCompile/CRANincoming/R-devel/pkgnet.Rcheck/tests_x64'
Error: ERROR: no packages specified …
```

Fix CRAN testing issues with R-devel

---

.travis.yml

I've been reading the [travis docs](https://docs.travis-ci.com/user/multi-os/) and I saw that you can test on Mac OSX on Travis! In this PR, I propose we test on both Linux (which I believe is Ubuntu in the travis testing farm) and OSX.

test on mac and linux

---

R/AbstractGraphReporter.R

Fixes a fickle bug where sometimes data.table complains when it executes this line:
https://github.com/UptakeOpenSource/pkgnet/blob/9a898614eeb52176228afcb9ec9d7d43ad6971c3/R/AbstractGraphReporter.R#L354
> Error in `[.data.table`(plotDTnodes, , `:=`(color, newPalette[.GRP]),  : 
'by' appears to evaluate to column names but isn't c() or key(). Use by=list(...) if you can. Otherwise, by=eval(get(colorFieldName)) should work. This is for efficiency so data.table can detect which columns are needed.

Fixed weird, inconsistent data.table error in group by

---

R/AbstractGraphReporter.R
R/PackageDependencyReporter.R
R/PackageFunctionReporter.R
tests/testthat/test-DependencyReporter.R
tests/testthat/test-FunctionReporter.R

In this PR, I propose removing all TODOs from our code and turning them into issues here on Github.
I would love to add a TODO-check to our CI but I'm not sure how to do that. You can edit the `script:` block in `.travis.yml` to configure what gets run, but I'm not sure what magic is happening to ensure that `R CMD CHECK` warnings result in build failures.
So for now, I just want to remove the existing TODOs and will open a separate issue for adding a CI step to prevent new ones from getting in.

removed TODOs from code

---

DESCRIPTION
_pkgdown.yml

https://enpiar.com/2017/11/21/getting-down-with-pkgdown/
https://pkgdown.r-lib.org/reference/build_site.html#yaml-config
`url` optionally specifies the url where the site will be published. Supplying this will:
- Allow other pkgdown sites will link to your site when needed, rather than using generic links to https://rdocumentation.org.
- Generate a sitemap.xml, increasing the searchability of your site.
- Automatically generate a CNAME when deploying to github.

add url and DocSearch info to improve searchability of pkgnet

---

NEWS.md
vignettes/publishing-reports.Rmd

- Updated NEWS.md with various changes from this release
- Changed link to example vignette in the "Publishing Your pkgnet Package Report" vignette (publishing-reports.Rmd) to point to a copy hosted in the gallery

NEWS.md and publishing-reports Vignette link change to gallery

---

DESCRIPTION
inst/baseballstats/DESCRIPTION
inst/sartre/DESCRIPTION

Soon `james.lamb@uptake.com` won't be a thing. Changing it here so all our docs will be correct.

changed to personal email address in DESCRIPTIONs

---

R/AbstractGraphReporter.R
tests/testthat/test-AbstractGraphReporter.R

While working on #244 , I noticed that the code for handling bad colors provided to `AbstractGraphReporter$set_plot_node_color_scheme()` is incorrect.
If you run the code I added in these unit tests (providing an invalid color), you'll get this cryptic error
```r
Error in areColors == FALSE : 
comparison (1) is possible only for atomic and list types
```
I didn't update NEWS since this is not a user-facing change.

fixed bug in set_plot_node_color_scheme()

---

R/FunctionReporter.R

Just added a simple row count check before comparing data table values.   Otherwise the result of the `data.table` command is `NA`

ensure inheritanceDT is nonempty before doing comparison.  Fixes #256

---

README.md

I think `pkgnet` has been around and in use long enough for us to remove the text in the README saying "this is a fairly new project". In this PR, I propose removing that language and making the tidyverse lifecycle badge a link to [the page explaining what "maturing" means](https://www.tidyverse.org/lifecycle/).

[docs] updated language about the maturity of the project

---

.travis.yml
CONTRIBUTING.md
DESCRIPTION
vignettes/pkgnet-intro.Rmd
vignettes/publishing-reports.Rmd

This pull request proposes two changes to speed up this project's CI:
* not installing `devtools`
* preferring precompiled binaries on Mac

[ci] remove devtools

---

py-pkg/pkgnet/abstract_graph_reporter.py

AbstractGraphReporter.network_measures should not be abstract. The change in this PR implements the same logic as in the R package. For now though, trying to call it will result in `pkg_graph.graph_measures()` raising a `NotImplementedError`, which is sensible. 
Fixes the issue reported here: https://github.com/uptake/pkgnet/issues/267#issuecomment-685457478

AbstractGraphReporter.network_measures should not be abstract

---

R/AbstractGraphReporter.R
R/AbstractPackageReporter.R
R/CreatePackageReport.R
R/GraphClasses.R
R/pkgnet.R
man/DependencyReporter.Rd
man/DirectedGraph.Rd
man/DirectedGraphMeasures.Rd
man/FunctionReporter.Rd
man/GraphClasses.Rd
man/InheritanceReporter.Rd
man/NetworkReporters.Rd
man/PackageReport.Rd
man/PackageReporters.Rd
man/SummaryReporter.Rd
man/pkgnet-package.Rd

removed redundant colons from docs

---

R/AbstractGraphReporter.R
R/AbstractPackageReporter.R
R/CreatePackageReport.R
R/GraphClasses.R
R/pkgnet.R
man/DependencyReporter.Rd
man/DirectedGraph.Rd
man/DirectedGraphMeasures.Rd
man/FunctionReporter.Rd
man/GraphClasses.Rd
man/InheritanceReporter.Rd
man/NetworkReporters.Rd
man/PackageReport.Rd
man/PackageReporters.Rd
man/SummaryReporter.Rd
man/pkgnet-package.Rd

I accidentally merged #284 into `master`, when it should have gone to `main`.
This merges its changes to `main`. I'll delete the `master` branch after this is merged.

removed redundant colons from docs (#284)

---

inst/package_report/package_dependency_reporter.Rmd

fixes #294
Corrects the legend text so that it matches the text in the actual legend.
```shell
R CMD install .
```
```r
pkgnet::CreatePackageReport("devtools")
```

correct legend text in dependency network (fixes #294)

---

.github/workflows/ci.yml
.github/workflows/smoke-tests.yaml
DESCRIPTION
tests/testthat/test-DependencyReporter-class.R
tests/testthat/test-DirectedGraph.R
tests/testthat/test-FunctionReporter-class.R
tests/testthat/test-InheritanceReporter-class.R
tests/testthat/testdata/node_measures_baseballstats_FunctionReporter.csv

This PR gets CICD tests back to working status after some updates in [rigraph](https://github.com/igraph/rigraph) and Ubuntu images caused job failures: 
- igraph updated their calculation of authorityScore in igraph release [0.10.5](https://github.com/igraph/igraph/releases/tag/0.10.5).  Consequently, some expected values in tests needed to change. 
- [rigraph](https://github.com/igraph/rigraph) deprecated `get.edgelist` and `get.vertex.attribute` functions. 
- added explicit [Tidy-html5](https://github.com/htacg/tidy-html5) import to github actions to resolve warning in R CMD Check on ubuntu.  Resolves #305

CICD Updates for Igraph changes and Ubuntu Tidy patch

---

NEWS.md
R/FunctionReporter.R
inst/baseballstats/R/batting_statistics.R

`do.call` with the function argument as string will now properly appear on the function reporter.  Previously, this would show as a `do.call` node with a circular reference. (#302)
This bit of code checks the recursion step for a list with a `do.call` call as the first element and a string as the second.  If true, it converts the string to a call, and then continues with the recursion.  
Note: `baseballstats` test package is changed, BUT because this do.call is in place, network remains identical.  Therefore, unit test for this edge case included.

extend to do.call case with func param as text (resolves #302)

---

NEWS.md
vignettes/pkgnet-intro.Rmd

Updated `pkgnet-intro` vignette to: 
- include information on the Class Inheritance Reporter (addressing #195)
- restructure the sections
- plug other pkgnet docs such as the [pkgnet Gallery](https://uptake.github.io/pkgnet-gallery/docs/articles/pkgnet-gallery.html) and the ["Publishing Your pkgnet Package Report" vignette](https://uptake.github.io/pkgnet/articles/publishing-reports.html)
- some minor edits and rewording

Updated pkgnet-intro vignette

---

NEWS.md
R/DependencyReporter.R
inst/milne/DESCRIPTION
tests/testthat/test-DependencyReporter-network.R
tests/testthat/testdata/milne_dependency_edges.csv
tests/testthat/testdata/milne_dependency_nodes.csv

This PR adds packages listed in the the "LinkingTo:" section of the `DESCRIPTION` file to the list of dependencies.  As noted in #303, these are overlooked today. Note, this also adds the recursive dependencies of the "LinkingTo:" packages to the graph.  
Our test package `milne` has had `Rcpp` added as a "LinkingTo:" dependency for unit testing.  Here's a look at `milne`'s dependency network before and after this change.
<table style="margin: 0px auto;">
<tr>
<td> <H1 >BEFORE</H1>
<td> <H1 >AFTER</H1>
<tr>
<td> <img src="https://github.com/uptake/pkgnet/assets/24531403/c439f0dc-c5a0-4bba-ba38-4b602916d92c"  alt="before" width = 95%" ></td>
<td><img src="https://github.com/uptake/pkgnet/assets/24531403/44e68a2e-1cf2-42c9-88c2-780c1d2a180c" alt="after" width = 95%"></td>
</tr> 
</table>
In …

adds LinkingTo items to dependency reporter (resolves #303)

---

.github/workflows/release.yml
DESCRIPTION
NEWS.md
cran-comments.md

This is a minor release that includes a number of new features, bug fixes and minor backwards compatible changes.  This PR will be fully merged AFTER it is CRAN accepted. 
* `do.call` with the function argument as string will now properly appear on the function reporter.  Previously, this would show as a `do.call` node with a circular reference. (#302)
* `LinkingTo:` package dependencies are now included in the `DependencyReporter` and subsequent HTML report and objects. (#319 Thanks @petergodbert !) 
* Updated `pkgnet-intro` vignette to include information on the Class Inheritance Reporter and other minor edits.    
* Recursive functions `.parse_function` and `.parse_R6_expression` made tolerant to control statemets like `break` or `next` that would break the recursion. (#322)   
* …

release v0.5.0

---

inst/package_report/package_report.Rmd

Caught by using 
```r
options(
warnPartialMatchArgs = TRUE,
warnPartialMatchDollar = TRUE,
warnPartialMatchAttr = TRUE
)
```

Avoid partial matching

---

.github/workflows/website.yaml
CONTRIBUTING.md

This edits the `website.yaml` workflow to build `docs/` from the last version tag (it is triggered after this event) and create a branch titled `website_docs_update`.  It will overwrite that branch if it exists already.  In this way, docs are ready to go for a PR, review & merge. 
In addition, I added a workflow file to update our gallery with a button push: https://github.com/uptake/pkgnet-gallery/pull/34
The gallery is kept separate for design decisions explained on that repo's README. 
Resolves #326

Button Push Website Build from Last Version Tag

---

NEWS.md
R/CreatePackageReport.R
R/testing_utils.R
tests/testthat.R
tests/testthat/test-0-test-package-installation.R
tests/testthat/test-Z-test-no-source-modifcations.R

This resolves #329 (thanks @jcarbaut for the catch!) 
Better detailed in the bug issue above, the issue is that when we called `rmarkdown::render` to render the report from an Rmd file within the installed package directory, it creates interim files within the installed package directory.  This is technically a CRAN violation.  It is rectified in line with `rmarkdown`'s recommendation for this issue which is to move all Rmd files to a temp directory and then call `rmarkdown::render` there. 
**Why didn't we catch this before?**
My money is on:
- The authors use more forgiving directories for installation, so missed the opportunity to catch this issue here.  
- Our test process involves installing `pkgnet` as well as all test packages in a temporary directory for testing.  Therefore, these …

Move rmarkdown::render action to happen in a temp directory
